### ISSUE TITLE
BoM lists incorrect jack?

### ISSUE THREAD

**Issue by akhepcat** [myriadrf/LimeSDR-USB#15]
Was trying to figure out what external power supply to get, and looked in the BoM  for the power jack so I could double-check my measurements.

The BoM at https://github.com/myriadrf/LimeSDR-USB/blob/master/hardware/plug/1v4/Project%20Outputs%20for%20LimeSDR-USB_1v4_LMS031pad/BOM/LimeSDR-USB_1v4_BOMr7.xls  (  the -r4 version as well )

lists a  2.1x5.5mm  power jack  -  however  the mounting dimensions on it are much smaller than the plug it fits, so my guess is that somebody pasted the wrong information.

My device *appears*  to have  a  3.0x1.1mm  jack 

Can this get corrected?

Also,  somebody should update the wiki with some guidance on the external power adapters so it's not so difficult to find.

Thanks

**Comment by ztamosevicius** [comment]
Component was OK, just description was wrong. BOM files updated, thank you for spotting this.

**Comment by akhepcat** [comment]
FWIW,  this adapter works fine with my Lime-USB: https://www.amazon.com/gp/product/B00Y7KOB8Q
