### ISSUE TITLE
Duplicated channel naming in schematic

### ISSUE THREAD

**Issue by alexwhittemore** [myriadrf/LimeSDR-USB#2]
On 05_LMS7002M_RF.SchDoc, the note "TXRF1_A" is duplicated twice. On the left, it looks like it should be as-is, and on the right (IC1 Part 5/5, attached to pins pa1op_2 and pa1on_2) I think it should be TXRF1_B.

**Comment by ztamosevicius** [comment]
Correct. It should be TXRF1_B next to the J2 connector.
Thanks for the note!

**Comment by ztamosevicius** [comment]
Fixed in v1.4 version.
