### ISSUE TITLE
Confusing TX channel labeling

### ISSUE THREAD

**Issue by alexwhittemore** [myriadrf/LimeSDR-USB#3]
Each of the two TX channels has two independent power amplifiers, with independent outputs, feeding independent matching networks for high and low frequency range.

It makes most sense to me to number the mutually exclusive channels, and to letter the frequency divisions of them. 

Specifically: (as-is name > proposed name)
TXRF1_A > TX1_L
TXRF1_B > TX2 _L
TXRF2_A > TX1_H
TXRF2_B > TX2_H

In fact, per current schematic, the net naming consistency seems poor - the channel noted "TXRF1_A" contains differential nets prefixed with "TXRF1," but so does the channel noted "TXRF2_A" right below it. This would be consistent with my "numbers for channels" convention requested above, but isn't consistent with the "letters for channels" convention currently in silk.

**Comment by ztamosevicius** [comment]
Agree. It will be improved for the next versions.
Thanks for review!

**Comment by zigastegu** [comment]
![image](https://cloud.githubusercontent.com/assets/1379063/20079590/aa30cb0e-a545-11e6-803d-28b9603db0fc.png)

Improved with latest commit 3d4a8c1e5b6626482928e8b3cf6abc6add5ede07

**Comment by ztamosevicius** [comment]
Improved in v1.4 version.
