### ISSUE TITLE
DDR reference plane

### ISSUE THREAD

**Issue by gitmodimo** [myriadrf/LimeSDR-USB#5]
Not all DDR signals have continuous reference plane. Signals on layer L4 L8 L9 from DDR to FPGA are crossing split plane. 

There are many references to that requirement:
4.1 http://www.ti.com/lit/an/spraaw8a/spraaw8a.pdf
25. http://www.nxp.com/files/32bit/doc/app_note/AN2910.pdf

Also clearance between polygon and DDR signals should be bigger.

**Comment by alexwhittemore** [comment]
Good catch! Although this might fall into the category of 'it works so, meh' - the memory is laid out very close to the FPGA, and it's pretty slow as modern technologies go, and there IS a continuous ground plane, just not on an immediately adjacent layer. The manufacturing notes only specify impedance control for USB 3 and RF between layers 1>2 and 11>bottom, so it looks like the memory isn't even designed to use impedance controlled routing, only length-matched. Which strikes me as fine - even given aggressive timing considerations, the trace length is well under a 1ns rise time in terms of propagation delay.

Plus, correct me if I'm wrong - I think this board's already been manufactured and is used in the wild, so unless there are memory errors showing up, it looks like real-world testing probably rules it out as problematic.

**Comment by gitmodimo** [comment]
I am not sure, but it seems that the boards are 'in the wild'. And yes if it works there is no need to change. But as for the FPGA project on github there is no DDR controller instantiation. In other words the firmware in current version does not use DDR at all. So that brings up the question whether it works. Are there any confirmed successful memtests?

**Comment by alexwhittemore** [comment]
Interesting, that doesn't inspire confidence, then. I suppose for the basic SDR use-case, it's not used? All the data is just piped directly through the USB controller. So you could be right, maybe it's just as-yet untested.

**Comment by ztamosevicius** [comment]
Exactly, for this use-case there is no need for external memories.
External memories are tested using massive write-read and compare procedure. No issues found so far.

**Comment by gitmodimo** [comment]
Thanks ztamosevicius. I think that settles it.

**Comment by alexwhittemore** [comment]
Hey, look at that, first closed issue :)
