### ISSUE TITLE
Changed BOM and placement of parts

### ISSUE THREAD

**Issue by zigastegu** [myriadrf/LimeSDR-USB#8]
Does recent change of BOM and placement affect "connector" position? With connector position I mean: both USB versions, DC socket, LEDs, u.fl conn
Thank you for support!

**Comment by Dovydas-R** [comment]
USB connector, DC socket and LEDs positions are the same.
u.fl RF connector slightly changed their positions due to additional components.
Also there is additional u.fl connector (REF_CLK_OUT).

**Comment by zigastegu** [comment]
Thank you for fast replay!

**Comment by luftek** [comment]
Is there a way you make a photo of new revision? :)

**Comment by zigastegu** [comment]
Is there a way you make a top side photo of new revision? :)

**Comment by Dovydas-R** [comment]
Today we uploaded project files for new board version. Enjoy :)
