### ISSUE TITLE
The LimeSDR board is broken?

### ISSUE THREAD

**Issue by Davonter** [myriadrf/LimeSDR-USB#9]
Hi, I wanna run OAI eNB use the board. Then I run the process, it aborted(core dump)!  I checked it, shows:
![tim 20170928173832](https://user-images.githubusercontent.com/19240391/30959821-e19f0906-a473-11e7-938c-c32b67e72d0b.png)

and the leds(2 red and 2 yellow) beside USB port keep bright always! Who can tell me the reason and help me sovle the problem, Thanks a lot!

**Comment by rjonaitis** [comment]
WestBridge name indicates the FX3 controller has not loaded firmware, check if the FX3 Boot jumper is in place. https://discourse.myriadrf.org/t/just-trying-to-get-started-having-no-luck/1127/13?u=ignasj

**Comment by Davonter** [comment]
Thanks! I have modified it successfully!
